image: node:18.14.0-bullseye-slim

stages:
 # - setup
  #- test
  - publish
  #- release

Publish TappSPA-TEST:
  stage: publish
  script:
    - npm ci --force
    - npm install -g firebase-tools --force
    - npm run build --prod
    - firebase login:ci --interactive
    - firebase deploy --token "$FIREBASE_TOKEN"
