image: node:18.14.0-bullseye

stages:
 # - setup
  #- test
  - publish
  - deploy

#setup-job:
#  stage: setup
#  script:
#    - npm ci --force

#unit-test-job:
#  stage: test
#  before_script:
#    - apt-get update
#    - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#    - apt-get install -y ./google-chrome-stable_current_amd64.deb
#    - export CHROME_BIN=/usr/bin/google-chrome
#  script:
#      - npm ci --force
#      - npm run test -- --no-watch --browsers=ChromeHeadlessCI

publish_test:
  stage: publish
  script:
    - npm ci --force
    - npm run build --prod
  artifacts:
    paths:
      - dist/