image: node:18.14.0-bullseye-slim

stages:
  - publish

install:
    stage: publish
    script:
        - npm ci --force
        - npm run build --prod
    artifacts:
        paths:
            - dist/
    environment:
        name: Test
        url: https://test.dylanwarrell.com



    
