name: Deploy to Production

on:
  push:
    branches: ["main"]
    paths:
      - 'tapp-client/**'
  workflow_dispatch:

jobs:
  install_and_build:
    runs-on: ubuntu-latest
    name: Install Dependencies and Build
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Restore dependencies from Cache
        uses: actions/cache@v4
        with:
          path: ./tapp-client/node_modules
          key: ${{ runner.OS }}-npm-${{ hashFiles('./tapp-client/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-

      - name: Install dependencies if missing/outdated
        run: npm install --prefix ./tapp-client/

      - name: Build for production
        run: npm run build-live --prefix ./tapp-client/

      - name: Archive production artifacts
        run: tar -czf dist.tar.gz -C ./tapp-client/ dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist.tar.gz
          retention-days: 1

  deploy:
    needs: [install_and_build]
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./tapp-client/

      - name: Extract build artifacts
        run: tar -xzf ./tapp-client/dist.tar.gz -C ./tapp-client/

      - name: Deploy to production server
        uses: appleboy/ftp-action@v2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./tapp-client/dist/
          remote-dir: /domains/dylanwarrell.com/public_html/tapp
          args: --delete
