name: Deploy to Live

on:
  push:
    branches: ["main"]

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install Dependencies
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install dependencies for Client
        run: npm install --prefix ./tapp-client/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: tapp-client/node_modules/

  build:
    needs: install
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Download dependencies
        uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: tapp-client/

      - name: Build for production
        run: npm run build-live --prefix ./tapp-client/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: tapp-client/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: tapp-client/dist/

      - name: Deploy to production server
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: liveDist # The branch name where you want to push the assets
          FOLDER: tapp-client/dist/ # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
