# .github/workflows/publish.yml
name: Deploy to Live

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install dependencies for Client
        run: npm install --prefix ./tapp-client/

      - name: Build for production
        run: npm run build-live --prefix ./tapp-client/

      - name: Deploy to production server
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: liveDist # The branch name where you want to push the assets
          FOLDER: dist/ # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
