name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [build/*]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install Dependencies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --prefix ./tapp-client/

      - name: Create archive of node modules
        run: zip -r node_modules.zip tapp-client/node_modules

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules.zip
          retention-days: 1

  build:
    runs-on: ubuntu-latest
    name: Build Tapp SPA
    needs: install

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download shared build artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: tapp-client

      - name: Create node_modules directory if it doesn't exist
        run: mkdir -p ./tapp-client/node_modules

      - name: Extract shared build archive
        run: unzip tapp-client/node_modules.zip -d ./tapp-client/node_modules

      - name: Add node_modules/.bin to PATH
        run: echo "$GITHUB_WORKSPACE/tapp-client/node_modules/.bin" >> $GITHUB_PATH

      - name: Build Tapp SPA
        run: npm run build-live --prefix ./tapp-client/
        
      - name: Create archive of build
        run: zip -r tapp-build.zip ./tapp-client/dist

      - name: Create and publish artifact of build
        uses: actions/upload-artifact@v4
        with:
          name: tapp-build
          path: tapp-build.zip
          retention-days: 7

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    if: always()  # Ensure the cleanup job runs regardless of the build job's outcome

    steps:
      - name: Delete node-modules artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: node_modules
