name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [build/*]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --prefix ./tapp-client/

      - name: Build Tapp SPA
        run: npm run build-live --prefix ./tapp-client/

      - name: Save build to shared directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/shared-build
          cp -r tapp-client/dist/* $GITHUB_WORKSPACE/shared-build/

  lint:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: List contents of shared build directory
      run: ls -la $GITHUB_WORKSPACE/shared-build  # List contents of shared-build

    - name: Use shared build directory
      run: |
        mkdir -p build
        cp -r $GITHUB_WORKSPACE/shared-build/* build/

    - name: Create and publish artifact of shared-build
      uses: actions/upload-artifact@v4
      with:
        name: shared-build
        path: $GITHUB_WORKSPACE/shared-build/

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: List contents of shared build directory
        run: ls -la $GITHUB_WORKSPACE/shared-build  # List contents of shared-build

      - name: Use shared build directory
        run: |
          mkdir -p build
          cp -r $GITHUB_WORKSPACE/shared-build/* build/

      - name: Create and publish artifact of shared-build
        uses: actions/upload-artifact@v4
        with:
          name: shared-build
          path: $GITHUB_WORKSPACE/shared-build/

  cleanup:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Delete shared build directory
        run: |
          rm -rf $GITHUB_WORKSPACE/shared-build
