name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [build/*]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --prefix ./tapp-client/

      - name: Create archive of shared build
        run: zip -r shared-build.zip tapp-client/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shared-build
          path: shared-build.zip
          retention-days: 1

  lint:
    runs-on: ubuntu-latest
    needs: install

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download shared build artifact
        uses: actions/download-artifact@v3
        with:
          name: shared-build
          path: .

      - name: Extract shared build archive
        run: unzip shared-build.zip -d Tapp-SPA/

      - name: Build Tapp SPA
        run: npm run build-live --prefix ./Tapp-SPA/

      - name: Create archive of build
        run: zip -r lint-build.zip Tapp-SPA/dist

      - name: Create and publish artifact of build
        uses: actions/upload-artifact@v4
        with:
          name: lint-build
          path: lint-build.zip
          retention-days: 7

  test:
    runs-on: ubuntu-latest
    needs: install

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download shared build artifact
        uses: actions/download-artifact@v3
        with:
          name: shared-build
          path: .

      - name: Extract shared build archive
        run: unzip shared-build.zip -d Tapp-SPA/

      - name: Build Tapp SPA
        run: npm run build-live --prefix ./Tapp-SPA/

      - name: Create archive of build
        run: zip -r lint-build.zip Tapp-SPA/dist

      - name: Create and publish artifact of build
        uses: actions/upload-artifact@v4
        with:
          name: lint-build
          path: lint-build.zip
          retention-days: 7
